import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import { TRPCReactProvider } from "@/trpc/client"

import "./globals.css";
import { Variable } from "lucide-react";

import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ["latin"]

})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TRPCReactProvider>
      <html
        lang="en" suppressHydrationWarning
        className={`${inter.className} antialiased`}
      >
        <body className="min-h-full flex flex-col">
          <Toaster />
          {children}
        </body>
      </html >
    </TRPCReactProvider>
  );
}
